### ISSUE TITLE
https://windwalker.io/documentation/ not available

### ISSUE THREAD

**Issue by GASOLINE** [ventoviro/windwalker-starter#9]
I tried many times to visite your site, no documentation. Just a blank page @ https://windwalker.io/documentation/

**Comment by asika32764** [comment]
It should auto redirect, if not, try visit this URL
https://windwalker.io/documentation/3.x/start/installation.html

**Comment by asika32764** [comment]
I found this issue only happened on the bottom documentation link and the menu item is works.

I fixed the redirect issue or the bottom link, please try again.
